name: lab3

on:
  push:
    branches:
      - feature/lab3
  workflow_dispatch:

jobs:
  lab3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Basic info
        run: |
          echo "Hello from GitHub Actions!"
          echo "Triggered by: $GITHUB_EVENT_NAME"
          echo "Branch: $GITHUB_REF_NAME"

      - name: System info
        run: |
          echo "OS"
          uname -a
          
          echo "CPU"
          lscpu | head -n 30
          
          echo "RAM"
          free -h
          
          echo "Disk"
          df -h

      - name: Runner Environment
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architecture: $RUNNER_ARCH"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Action: $GITHUB_ACTION"
